Repository StanHaakman/MongoDB-to-RationalDB, pull requests merged in 2021-02, with the labels that each got.

#2 Alle data printen voor opdracht 2a
  main.py
Labels: enhancement

#3 Vervolg
  classes/_data_recieve.py
  main.py
Labels: bug, documentation

#4 Create Relations.txt
  Relations.txt
Labels: documentation

#5 Stan/opdracht2c
  classes/_data_recieve.py
  main.py
Labels: Classes, enhancement

#6 Creeer file voor het testen van de postgres database connectie en versie
  classes/tests/_test_postgresqConnectie.py
Labels: SQL

#7 file toevoegen aan de git ignore voor de prive gegevens van de databases
  .gitignore
  classes/tests/_test_postgresqConnectie.py
Labels: SQL

#10 connectie tussen python en postgres opgezet en data van mongodb naar …
  youssef/config.py
  youssef/connectie.py
  youssef/create_table.py
  youssef/database.ini
  youssef/overschrijven.py
Labels: extend_code

#11 Relations txt/update
  Relations.txt
Labels: documentation, enhancement
