Repository StanHaakman/MongoDB-to-RationalDB, pull requests merged in 2021-03, with the labels that each got.

#14 Data converter
  .gitignore
  huwebshop.sql
Labels: SQL

#17 Data converter bugfix
  classes/_data_converter.py
  main.py
Labels: bug, enhancement

#20 Products bewerken
  classes/_data_converter.py
  functions/products_bewerken.py
  main.py
  overige/config.py
  overige/connectie.py
  overige/create_table.py
  overige/database.ini
  overige/overschrijven.py
Labels: SQL

#22 gender in dataset verbeterd. script algemeen geconctroleerd.
  classes/_sql_aanmaken.py
  functions/products_bewerken.py
  main.py
Labels: enhancement

#23 Add files via upload
  The_process_and_problems_of_creating_a_database.pdf
Labels: documentation

#24 Visitors bewerken
  functions/products_bewerken.py
  functions/visitors_bewerken.py
  main.py
Labels: enhancement, extend_code

#28 buid in sessies aangepast. eerste twee en laatste twee karakters per …
  functions/sessions_bewerken.py
Labels: SQL, bug, enhancement, extend_code

#29 script voor verbeteren dat products-dataset verbeterd.
  functions/products_bewerken.py
Labels: SQL, bug

#30 Sqlquery
  .gitignore
  classes/_data_converter.py
  classes/_data_sender.py
  classes/_sql_aanmaken.py
  functions/products_bewerken.py
  functions/sessions_bewerken.py
  functions/visitors_bewerken.py
  huwebshop.sql
  main.py
  overige/config.py
  overige/connectie.py
  overige/create_table.py
  overige/database.ini
  overige/overschrijven.py
Labels: Classes, SQL, bug, documentation, enhancement, extend_code
